=== symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns="http://symfony.com/schema/dic/services"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     targetNamespace="http://symfony.com/schema/dic/services"
     elementFormDefault="qualified">

  <xsd:annotation>
    <xsd:documentation><![CDATA[
      Symfony XML Services Schema, version 1.0
      Authors: Fabien Potencier

      This defines a way to describe PHP objects (services) and their
      dependencies.
    ]]></xsd:documentation>
  </xsd:annotation>

  <xsd:element name="container" type="container" />

  <xsd:complexType name="container">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
        The root element of a service file.
      ]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:group ref="foreign" />
      <xsd:sequence minOccurs="0">
        <xsd:element name="imports" type="imports" />
        <xsd:group ref="foreign" />
      </xsd:sequence>
      <xsd:sequence minOccurs="0">
        <xsd:element name="parameters" type="parameters" />
        <xsd:group ref="foreign" />
      </xsd:sequence>
      <xsd:sequence minOccurs="0">
        <xsd:element name="services" type="services" />
        <xsd:group ref="foreign" />
      </xsd:sequence>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:group name="foreign">
    <xsd:sequence>
      <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:group>

  <xsd:complexType name="services">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
        Enclosing element for the definition of all services
      ]]></xsd:documentation>
    </xsd:annotation>
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="service" type="service" minOccurs="1" />
      <xsd:element name="prototype" type="prototype" minOccurs="0" />
      <xsd:element name="defaults" type="defaults" minOccurs="0" maxOccurs="1" />
      <xsd:element name="instanceof" type="instanceof" minOccurs="0" />
      <xsd:element name="stack" type="stack" minOccurs="0" />
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="imports">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
        Enclosing element for the import elements
      ]]></xsd:documentation>
    </xsd:annotation>
    <xsd:choice minOccurs="1" maxOccurs="unbounded">
      <xsd:element name="import" type="import" />
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="import">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
        Import an external resource defining other services or parameters
      ]]></xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="resource" type="xsd:string" use="required" />
    <xsd:attribute name="ignore-errors" type="ignore_errors" />
    <xsd:attribute name="type" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="callable">
    <xsd:choice minOccurs="0" maxOccurs="1">
      <xsd:element name="service" type="service" minOccurs="0" maxOccurs="1" />
    </xsd:choice>
    <xsd:attribute name="service" type="xsd:string" />
    <xsd:attribute name="class" type="xsd:string" />
    <xsd:attribute name="method" type="xsd:string" />
    <xsd:attribute name="function" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="defaults">
    <xsd:annotation>
      <xsd:documentation><![CDATA[
        Enclosing element for the service definitions' defaults for the current file
      ]]></xsd:documentation>
    </xsd:annotation>
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="tag" type="tag" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="bind" type="bind" minOccurs="0" maxOccurs="unbounded" />
    </xsd:choice>
    <xsd:attribute name="public" type="boolean" />
    <xsd:attribute name="autowire" type="boolean" />
    <xsd:attribute name="autoconfigure" type="boolean" />
  </xsd:complexType>

  <xsd:complexType name="service">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="configurator" type="callable" minOccurs="0" maxOccurs="1" />
      <xsd:element name="factory" type="callable" minOccurs="0" maxOccurs="1" />
      <xsd:element name="deprecated" type="deprecated" minOccurs="0" maxOccurs="1" />
      <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="tag" type="tag" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="bind" type="bind" minOccurs="0" maxOccurs="unbounded" />
    </xsd:choice>
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="class" type="xsd:string" />
    <xsd:attribute name="shared" type="boolean" />
    <xsd:attribute name="public" type="boolean" />
    <xsd:attribute name="synthetic" type="boolean" />
    <xsd:attribute name="lazy" type="xsd:string" />
    <xsd:attribute name="abstract" type="boolean" />
    <xsd:attribute name="alias" type="xsd:string" />
    <xsd:attribute name="parent" type="xsd:string" />
    <xsd:attribute name="decorates" type="xsd:string" />
    <xsd:attribute name="decoration-on-invalid" type="invalid_decorated_service_sequence" />
    <xsd:attribute name="decoration-inner-name" type="xsd:string" />
    <xsd:attribute name="decoration-priority" type="xsd:integer" />
    <xsd:attribute name="autowire" type="boolean" />
    <xsd:attribute name="autoconfigure" type="boolean" />
  </xsd:complexType>

  <xsd:complexType name="instanceof">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="configurator" type="callable" minOccurs="0" maxOccurs="1" />
      <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="tag" type="tag" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="bind" type="bind" minOccurs="0" maxOccurs="unbounded" />
    </xsd:choice>
    <xsd:attribute name="id" type="xsd:string" use="required" />
    <xsd:attribute name="shared" type="boolean" />
    <xsd:attribute name="public" type="boolean" />
    <xsd:attribute name="lazy" type="xsd:string" />
    <xsd:attribute name="autowire" type="boolean" />
    <xsd:attribute name="autoconfigure" type="boolean" />
  </xsd:complexType>

  <xsd:complexType name="prototype">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="configurator" type="callable" minOccurs="0" maxOccurs="1" />
      <xsd:element name="factory" type="callable" minOccurs="0" maxOccurs="1" />
      <xsd:element name="deprecated" type="deprecated" minOccurs="0" maxOccurs="1" />
      <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="tag" type="tag" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="bind" type="bind" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="exclude" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
    </xsd:choice>
    <xsd:attribute name="namespace" type="xsd:string" use="required" />
    <xsd:attribute name="resource" type="xsd:string" use="required" />
    <xsd:attribute name="exclude" type="xsd:string" />
    <xsd:attribute name="shared" type="boolean" />
    <xsd:attribute name="public" type="boolean" />
    <xsd:attribute name="lazy" type="xsd:string" />
    <xsd:attribute name="abstract" type="boolean" />
    <xsd:attribute name="parent" type="xsd:string" />
    <xsd:attribute name="autowire" type="boolean" />
    <xsd:attribute name="autoconfigure" type="boolean" />
  </xsd:complexType>

  <xsd:complexType name="stack">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="service" type="service" minOccurs="1" />
      <xsd:element name="deprecated" type="deprecated" minOccurs="0" maxOccurs="1" />
    </xsd:choice>
    <xsd:attribute name="id" type="xsd:string" use="required" />
    <xsd:attribute name="public" type="boolean" />
  </xsd:complexType>

  <xsd:complexType name="tag">
    <xsd:choice minOccurs="0">
      <xsd:element name="attribute" type="tag_attribute" maxOccurs="unbounded" />
    </xsd:choice>
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:anyAttribute namespace="##any" processContents="lax" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="deprecated">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <!-- In Symfony 6, make these attributes required -->
        <xsd:attribute name="package" type="xsd:string" />
        <xsd:attribute name="version" type="xsd:string" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="tag_attribute">
    <xsd:choice minOccurs="0">
      <xsd:element name="attribute" type="tag_attribute" maxOccurs="unbounded" />
    </xsd:choice>
    <xsd:attribute name="name" type="xsd:string" use="required" />
  </xsd:complexType>

  <xsd:complexType name="parameters">
    <xsd:choice minOccurs="1" maxOccurs="unbounded">
      <xsd:element name="parameter" type="parameter" />
    </xsd:choice>
    <xsd:attribute name="type" type="parameter_type" />
    <xsd:attribute name="key" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="parameter" mixed="true">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="parameter" type="parameter" />
    </xsd:choice>
    <xsd:attribute name="type" type="parameter_type" />
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="key" type="xsd:string" />
    <xsd:attribute name="on-invalid" type="invalid_sequence" />
  </xsd:complexType>

  <xsd:complexType name="property" mixed="true">
    <xsd:choice minOccurs="0">
      <xsd:element name="property" type="property" maxOccurs="unbounded" />
      <xsd:element name="service" type="service" />
    </xsd:choice>
    <xsd:attribute name="type" type="argument_type" />
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="key" type="xsd:string" />
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="on-invalid" type="invalid_sequence" />
    <xsd:attribute name="tag" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="bind" mixed="true">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="bind" type="argument" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="service" type="service" />
    </xsd:choice>
    <xsd:attribute name="type" type="argument_type" />
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="key" type="xsd:string" use="required" />
    <xsd:attribute name="on-invalid" type="invalid_sequence" />
    <xsd:attribute name="method" type="xsd:string" />
    <xsd:attribute name="tag" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="argument" mixed="true">
    <xsd:choice minOccurs="0">
      <xsd:element name="argument" type="argument" maxOccurs="unbounded" />
      <xsd:element name="service" type="service" />
    </xsd:choice>
    <xsd:attribute name="type" type="argument_type" />
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="key" type="xsd:string" />
    <xsd:attribute name="index" type="xsd:integer" />
    <xsd:attribute name="on-invalid" type="invalid_sequence" />
    <xsd:attribute name="tag" type="xsd:string" />
    <xsd:attribute name="index-by" type="xsd:string" />
    <xsd:attribute name="default-index-method" type="xsd:string" />
    <xsd:attribute name="default-priority-method" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="call">
    <xsd:choice minOccurs="0">
      <xsd:element name="argument" type="argument" maxOccurs="unbounded" />
    </xsd:choice>
    <xsd:attribute name="method" type="xsd:string" />
    <xsd:attribute name="returns-clone" type="boolean" />
  </xsd:complexType>

  <xsd:simpleType name="parameter_type">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="collection" />
      <xsd:enumeration value="string" />
      <xsd:enumeration value="constant" />
      <xsd:enumeration value="binary" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="argument_type">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="abstract" />
      <xsd:enumeration value="collection" />
      <xsd:enumeration value="service" />
      <xsd:enumeration value="expression" />
      <xsd:enumeration value="string" />
      <xsd:enumeration value="constant" />
      <xsd:enumeration value="binary" />
      <xsd:enumeration value="iterator" />
      <xsd:enumeration value="service_locator" />
      <!-- "tagged" is an alias of "tagged_iterator", using "tagged_iterator" is preferred. -->
      <xsd:enumeration value="tagged" />
      <xsd:enumeration value="tagged_iterator" />
      <xsd:enumeration value="tagged_locator" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ignore_errors">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="(true|false|not_found)" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="invalid_sequence">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="null" />
      <xsd:enumeration value="ignore" />
      <xsd:enumeration value="exception" />
      <xsd:enumeration value="ignore_uninitialized" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="invalid_decorated_service_sequence">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="null" />
      <xsd:enumeration value="ignore" />
      <xsd:enumeration value="exception" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="boolean">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="(%.+%|true|false)" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== symfony/symfony/src/Symfony/Bundle/AsseticBundle/Resources/config/assetic.xml
<?xml version="1.0" ?>

<container xmlns="http://www.symfony-project.org/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.symfony-project.org/schema/dic/services http://www.symfony-project.org/schema/dic/services/services-1.0.xsd">

    <parameters>
        <parameter key="assetic.asset_factory.class">Symfony\Bundle\AsseticBundle\Factory\AssetFactory</parameter>
        <parameter key="assetic.asset_manager.class">Assetic\Factory\LazyAssetManager</parameter>
        <parameter key="assetic.filter_manager.class">Symfony\Bundle\AsseticBundle\FilterManager</parameter>
        <parameter key="assetic.cached_formula_loader.class">Assetic\Factory\Loader\CachedFormulaLoader</parameter>
        <parameter key="assetic.config_cache.class">Assetic\Cache\ConfigCache</parameter>
        <parameter key="assetic.asset_manager_cache_warmer.class">Symfony\Bundle\AsseticBundle\CacheWarmer\AssetManagerCacheWarmer</parameter>
        <parameter key="assetic.directory_resource.class">Symfony\Bundle\AsseticBundle\Factory\DirectoryResource</parameter>

        <parameter key="assetic.filter.coffee.class">Assetic\Filter\CoffeeScriptFilter</parameter>
        <parameter key="assetic.filter.cssrewrite.class">Assetic\Filter\CssRewriteFilter</parameter>
        <parameter key="assetic.filter.google_closure_compiler_api.class">Assetic\Filter\GoogleClosure\CompilerApiFilter</parameter>
        <parameter key="assetic.filter.google_closure_compiler_jar.class">Assetic\Filter\GoogleClosure\CompilerJarFilter</parameter>
        <parameter key="assetic.filter.less.class">Assetic\Filter\LessFilter</parameter>
        <parameter key="assetic.filter.sass.class">Assetic\Filter\Sass\SassFilter</parameter>
        <parameter key="assetic.filter.scss.class">Assetic\Filter\Sass\ScssFilter</parameter>
        <parameter key="assetic.filter.sprockets.class">Assetic\Filter\SprocketsFilter</parameter>

        <parameter key="assetic.java_bin">/usr/bin/java</parameter>
        <parameter key="assetic.sass_bin">/usr/bin/sass</parameter>
        <parameter key="assetic.node_bin">/usr/bin/node</parameter>
        <parameter key="assetic.node_paths" type="collection"></parameter>
        <parameter key="assetic.sprocketize_bin">/usr/bin/sprocketize</parameter>
        <parameter key="assetic.coffee_bin">/usr/bin/coffee</parameter>

        <parameter key="assetic.cache_dir">%kernel.cache_dir%/assetic</parameter>
    </parameters>

    <services>
        <!-- managers -->
        <service id="assetic.filter_manager" class="%assetic.filter_manager.class%">
            <argument type="service" id="service_container" />
            <argument type="collection"></argument>
        </service>
        <service id="assetic.asset_manager" class="%assetic.asset_manager.class%">
            <argument type="service" id="assetic.asset_factory" />
            <argument type="collection"></argument>
        </service>
        <service id="assetic.asset_factory" class="%assetic.asset_factory.class%" public="false">
            <argument type="service" id="kernel" />
            <argument>%assetic.document_root%</argument>
            <argument>%assetic.debug%</argument>
            <call method="setFilterManager"><argument type="service" id="assetic.filter_manager" /></call>
        </service>

        <!-- filters -->
        <service id="assetic.filter.cssrewrite" class="%assetic.filter.cssrewrite.class%">
            <tag name="assetic.filter" alias="cssrewrite" />
            <argument type="service" id="assetic.css_tokenizer" />
        </service>
        <service id="assetic.filter.less" class="%assetic.filter.less.class%">
            <tag name="assetic.filter" alias="less" />
            <argument>%assetic.document_root%</argument>
            <argument>%assetic.node_bin%</argument>
            <argument>%assetic.node_paths%</argument>
        </service>
        <service id="assetic.filter.sass" class="%assetic.filter.sass.class%">
            <tag name="assetic.filter" alias="sass" />
            <argument>%assetic.sass_bin%</argument>
        </service>
        <service id="assetic.filter.scss" class="%assetic.filter.scss.class%">
            <tag name="assetic.filter" alias="scss" />
            <argument>%assetic.sass_bin%</argument>
        </service>
        <service id="assetic.filter.google_closure_compiler" class="%assetic.filter.google_closure_compiler_api.class%">
            <tag name="assetic.filter" alias="closure" />
        </service>
        <service id="assetic.filter.sprockets" class="%assetic.filter.sprockets.class%">
            <tag name="assetic.filter" alias="sprockets" />
            <argument>%assetic.document_root%</argument>
            <argument>%assetic.sprocketize_bin%</argument>
        </service>
        <service id="assetic.filter.coffee" class="%assetic.filter.coffee.class%">
            <tag name="assetic.filter" alias="coffee" />
            <argument>%assetic.coffee_bin%</argument>
            <argument>%assetic.node_bin%</argument>
        </service>

        <!-- other -->
        <service id="assetic.css_tokenizer" class="PHP_CodeSniffer_Tokenizers_CSS" public="false">
            <file>PHP/CodeSniffer.php</file>
        </service>
        <service id="assetic.config_cache" class="%assetic.config_cache.class%" public="false">
            <argument>%assetic.cache_dir%/config</argument>
        </service>
        <service id="assetic.asset_manager_cache_warmer" class="%assetic.asset_manager_cache_warmer.class%" public="false">
            <tag name="kernel.cache_warmer" priority="10" />
            <argument type="service" id="assetic.asset_manager" />
        </service>
    </services>
</container>

=== symfony/symfony/src/Symfony/Bundle/AsseticBundle/Resources/config/templating_php.xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <parameters>
        <parameter key="assetic.helper.dynamic.class">Symfony\Bundle\AsseticBundle\Templating\DynamicAsseticHelper</parameter>
        <parameter key="assetic.helper.static.class">Symfony\Bundle\AsseticBundle\Templating\StaticAsseticHelper</parameter>
        <parameter key="assetic.php_formula_loader.class">Symfony\Bundle\AsseticBundle\Factory\Loader\AsseticHelperFormulaLoader</parameter>
    </parameters>

    <services>
        <service id="assetic.helper.dynamic" class="%assetic.helper.dynamic.class%">
            <tag name="assetic.templating.php" />
            <argument type="service" id="templating.helper.router" />
            <argument type="service" id="assetic.asset_factory" />
            <argument>%assetic.debug%</argument>
        </service>

        <service id="assetic.helper.static" class="%assetic.helper.static.class%">
            <tag name="assetic.templating.php" />
            <argument type="service" id="templating.helper.assets" />
            <argument type="service" id="assetic.asset_factory" />
            <argument>%assetic.debug%</argument>
        </service>

        <service id="assetic.php_formula_loader" class="%assetic.cached_formula_loader.class%" public="false">
            <tag name="assetic.formula_loader" alias="php" />
            <tag name="assetic.templating.php" />
            <argument type="service" id="assetic.php_formula_loader.real" />
            <argument type="service" id="assetic.config_cache" />
            <argument>%kernel.debug%</argument>
        </service>

        <service id="assetic.php_formula_loader.real" class="%assetic.php_formula_loader.class%" public="false">
            <tag name="assetic.templating.php" />
            <argument type="service" id="assetic.asset_factory" />
        </service>
    </services>
</container>

=== symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/templating.xml
<?xml version="1.0" ?>

<container xmlns="http://www.symfony-project.org/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.symfony-project.org/schema/dic/services http://www.symfony-project.org/schema/dic/services/services-1.0.xsd">

    <parameters>
        <parameter key="templating.engine.delegating.class">Symfony\Bundle\FrameworkBundle\Templating\DelegatingEngine</parameter>
        <parameter key="templating.name_parser.class">Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser</parameter>
        <parameter key="templating.cache_warmer.template_paths.class">Symfony\Bundle\FrameworkBundle\CacheWarmer\TemplatePathsCacheWarmer</parameter>
        <parameter key="templating.locator.class">Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator</parameter>
        <parameter key="templating.locator.cached.class">Symfony\Bundle\FrameworkBundle\Templating\Loader\CachedTemplateLocator</parameter>
        <parameter key="templating.loader.filesystem.class">Symfony\Bundle\FrameworkBundle\Templating\Loader\FilesystemLoader</parameter>
        <parameter key="templating.loader.cache.class">Symfony\Component\Templating\Loader\CacheLoader</parameter>
        <parameter key="templating.loader.chain.class">Symfony\Component\Templating\Loader\ChainLoader</parameter>
        <parameter key="templating.assets.version">null</parameter>
        <parameter key="templating.assets.base_urls" type="collection"></parameter>
        <parameter key="debug.file_link_format">null</parameter>
    </parameters>

    <services>
        <service id="templating.engine.delegating" class="%templating.engine.delegating.class%" public="false">
            <argument type="service" id="service_container" />
            <argument type="collection" />
        </service>

        <service id="templating.name_parser" class="%templating.name_parser.class%">
            <argument type="service" id="kernel" />
        </service>

        <service id="templating.locator" class="%templating.locator.class%" public="false">
            <argument type="service" id="file_locator" />
            <argument>%kernel.root_dir%</argument>
        </service>

        <service id="templating.locator.cached" class="%templating.locator.cached.class%" public="false">
            <argument>%kernel.cache_dir%</argument>
        </service>

        <service id="templating.cache_warmer.template_paths" class="%templating.cache_warmer.template_paths.class%" public="false">
            <argument type="service" id="kernel" />
            <argument type="service" id="file_locator" />
            <argument type="service" id="templating.name_parser" />
            <argument>%kernel.root_dir%/views</argument>
        </service>

        <service id="templating.loader.filesystem" class="%templating.loader.filesystem.class%" public="false">
            <argument type="service" id="templating.locator" />
        </service>

        <service id="templating.loader.cache" class="%templating.loader.cache.class%" public="false">
            <argument type="service" id="templating.loader.wrapped" />
            <argument>%templating.loader.cache.path%</argument>
            <call method="setDebugger"><argument type="service" id="templating.debugger" on-invalid="ignore" /></call>
        </service>

        <service id="templating.loader.chain" class="%templating.loader.chain.class%" public="false">
            <call method="setDebugger"><argument type="service" id="templating.debugger" on-invalid="ignore" /></call>
        </service>

        <service id="templating.loader" alias="templating.loader.filesystem" />
    </services>
</container>

=== symfony/symfony/src/Symfony/Bundle/SwiftmailerBundle/Resources/config/smtp.xml
<?xml version="1.0" encoding="UTF-8" ?>

<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <parameters>
        <parameter key="swiftmailer.transport.smtp.class">Swift_Transport_EsmtpTransport</parameter>
    </parameters>

    <services>
        <service id="swiftmailer.transport.smtp" class="%swiftmailer.transport.smtp.class%" public="false">
            <argument type="service" id="swiftmailer.transport.buffer" />
            <argument type="collection">
                <argument type="service" id="swiftmailer.transport.authhandler" />
            </argument>
            <argument type="service" id="swiftmailer.transport.eventdispatcher" />

            <call method="setHost"><argument>%swiftmailer.transport.smtp.host%</argument></call>
            <call method="setPort"><argument>%swiftmailer.transport.smtp.port%</argument></call>
            <call method="setEncryption"><argument>%swiftmailer.transport.smtp.encryption%</argument></call>
            <call method="setUsername"><argument>%swiftmailer.transport.smtp.username%</argument></call>
            <call method="setPassword"><argument>%swiftmailer.transport.smtp.password%</argument></call>
            <call method="setAuthMode"><argument>%swiftmailer.transport.smtp.auth_mode%</argument></call>
        </service>
    </services>
</container>

=== symfony/symfony/src/Symfony/Bundle/SecurityBundle/Resources/config/guard.xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="security.authentication.guard_handler"
                 class="Symfony\Component\Security\Guard\GuardAuthenticatorHandler"
            >
            <argument type="service" id="security.token_storage" />
            <argument type="service" id="event_dispatcher" on-invalid="null" />
        </service>

        <!-- See GuardAuthenticationFactory -->
        <service id="security.authentication.provider.guard"
                 class="Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider"
                 abstract="true"
                 public="false"
            >
            <argument /> <!-- Simple Authenticator -->
            <argument /> <!-- User Provider -->
            <argument /> <!-- Provider-shared Key -->
            <argument /> <!-- User Checker -->
        </service>

        <service id="security.authentication.listener.guard"
                 class="Symfony\Component\Security\Guard\Firewall\GuardAuthenticationListener"
                 public="false"
                 abstract="true"
            >
            <tag name="monolog.logger" channel="security" />
            <argument type="service" id="security.authentication.guard_handler" />
            <argument type="service" id="security.authentication.manager" />
            <argument /> <!-- Provider-shared Key -->
            <argument /> <!-- Authenticator -->
            <argument type="service" id="logger" on-invalid="null" />
        </service>
    </services>
</container>
