=== symfony/symfony/src/Symfony/Component/Routing/Loader/schema/routing/routing-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns="http://symfony.com/schema/routing"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://symfony.com/schema/routing"
    elementFormDefault="qualified">

  <xsd:annotation>
    <xsd:documentation><![CDATA[
      Symfony XML Routing Schema, version 1.0
      Authors: Fabien Potencier, Tobias Schultze

      This scheme defines the elements and attributes that can be used to define
      routes. A route maps an HTTP request to a set of configuration variables.
    ]]></xsd:documentation>
  </xsd:annotation>

  <xsd:element name="routes" type="routes" />

  <xsd:complexType name="routes">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="import" type="import" />
      <xsd:element name="route" type="route" />
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="localized-path">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="locale" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:group name="configs">
    <xsd:choice>
      <xsd:element name="default" nillable="true" type="default" />
      <xsd:element name="requirement" type="element" />
      <xsd:element name="option" type="element" />
      <xsd:element name="condition" type="xsd:string" />
    </xsd:choice>
  </xsd:group>

  <xsd:complexType name="route">
    <xsd:sequence>
      <xsd:group ref="configs" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="path" type="localized-path" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required" />
    <xsd:attribute name="path" type="xsd:string" />
    <xsd:attribute name="host" type="xsd:string" />
    <xsd:attribute name="schemes" type="xsd:string" />
    <xsd:attribute name="methods" type="xsd:string" />
    <xsd:attribute name="controller" type="xsd:string" />
    <xsd:attribute name="locale" type="xsd:string" />
    <xsd:attribute name="format" type="xsd:string" />
    <xsd:attribute name="utf8" type="xsd:boolean" />
  </xsd:complexType>

  <xsd:complexType name="import">
    <xsd:sequence maxOccurs="unbounded" minOccurs="0">
      <xsd:group ref="configs" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="prefix" type="localized-path" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="exclude" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="resource" type="xsd:string" use="required" />
    <xsd:attribute name="type" type="xsd:string" />
    <xsd:attribute name="exclude" type="xsd:string" />
    <xsd:attribute name="prefix" type="xsd:string" />
    <xsd:attribute name="name-prefix" type="xsd:string" />
    <xsd:attribute name="host" type="xsd:string" />
    <xsd:attribute name="schemes" type="xsd:string" />
    <xsd:attribute name="methods" type="xsd:string" />
    <xsd:attribute name="controller" type="xsd:string" />
    <xsd:attribute name="locale" type="xsd:string" />
    <xsd:attribute name="format" type="xsd:string" />
    <xsd:attribute name="trailing-slash-on-root" type="xsd:boolean" />
    <xsd:attribute name="utf8" type="xsd:boolean" />
  </xsd:complexType>

  <xsd:complexType name="default" mixed="true">
    <xsd:choice minOccurs="0" maxOccurs="1">
      <xsd:element name="bool" type="xsd:boolean" />
      <xsd:element name="int" type="xsd:integer" />
      <xsd:element name="float" type="xsd:float" />
      <xsd:element name="string" type="xsd:string" />
      <xsd:element name="list" type="list" />
      <xsd:element name="map" type="map" />
    </xsd:choice>
    <xsd:attribute name="key" type="xsd:string" use="required" />
  </xsd:complexType>

  <xsd:complexType name="element">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="key" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="list">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="bool" nillable="true" type="xsd:boolean" />
      <xsd:element name="int" nillable="true" type="xsd:integer" />
      <xsd:element name="float" nillable="true" type="xsd:float" />
      <xsd:element name="string" nillable="true" type="xsd:string" />
      <xsd:element name="list" nillable="true" type="list" />
      <xsd:element name="map" nillable="true" type="map" />
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="map">
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
          <xsd:element name="bool" nillable="true" type="map-bool-entry" />
          <xsd:element name="int" nillable="true" type="map-int-entry" />
          <xsd:element name="float" nillable="true" type="map-float-entry" />
          <xsd:element name="string" nillable="true" type="map-string-entry" />
          <xsd:element name="list" nillable="true" type="map-list-entry" />
          <xsd:element name="map" nillable="true" type="map-map-entry" />
      </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="map-bool-entry">
    <xsd:simpleContent>
      <xsd:extension base="xsd:boolean">
        <xsd:attribute name="key" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="map-int-entry">
    <xsd:simpleContent>
      <xsd:extension base="xsd:integer">
        <xsd:attribute name="key" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="map-float-entry">
    <xsd:simpleContent>
      <xsd:extension base="xsd:float">
        <xsd:attribute name="key" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="map-string-entry">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="key" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="map-list-entry">
    <xsd:complexContent>
      <xsd:extension base="list">
        <xsd:attribute name="key" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="map-map-entry">
    <xsd:complexContent>
      <xsd:extension base="map">
        <xsd:attribute name="key" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== symfony/symfony/src/Symfony/Component/Routing/Tests/Fixtures/validpattern.xml
<?xml version="1.0" encoding="UTF-8" ?>

<routes xmlns="http://symfony.com/schema/routing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/routing https://symfony.com/schema/routing/routing-1.0.xsd">

    <route id="blog_show" path="/blog/{slug}" host="{locale}.example.com" methods="GET|POST  put,OpTiOnS" schemes="hTTps">
        <default key="_controller">MyBundle:Blog:show</default>
        <default key="_stateless">
            <bool>true</bool>
        </default>
        <requirement key="locale">\w+</requirement>
        <option key="compiler_class">RouteCompiler</option>
        <condition>context.getMethod() == "GET"</condition>
    </route>

    <route id="blog_show_inherited" path="/blog/{slug}">
        <condition>context.getMethod() == "GET"</condition>
    </route>
</routes>

=== symfony/symfony/src/Symfony/Component/Routing/Tests/Fixtures/exporter/routing.xml
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns="http://symfony.com/schema/routing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/routing http://symfony.com/schema/routing/routing-1.0.xsd">
  <route id="foo" path="/foo/{bar}">
    <default key="def">test</default>
    <requirement key="bar">baz|symfony</requirement>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="foobar" path="/foo/{bar}">
    <default key="bar">toto</default>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="bar" path="/bar/{foo}" methods="GET, HEAD">
    <requirement key="_method">GET|head</requirement>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baragain" path="/baragain/{foo}" methods="GET, POST">
    <requirement key="_method">get|post</requirement>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz" path="/test/baz">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz2" path="/test/baz.html">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz3" path="/test/baz3/">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz4" path="/test/{foo}/">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz5" path="/test/{foo}/" methods="GET">
    <requirement key="_method">get</requirement>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz5unsafe" path="/testunsafe/{foo}/" methods="POST">
    <requirement key="_method">post</requirement>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz6" path="/test/baz">
    <default key="foo">bar baz</default>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz7" path="/te st/baz">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz8" path="/te\ st/baz">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="baz9" path="/test/{baz}">
    <requirement key="baz">te\\ st</requirement>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route1" path="/route1" host="a.example.com">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route2" path="/c2/route2" host="a.example.com">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route3" path="/c2/route3" host="b.example.com">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route4" path="/route4" host="a.example.com">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route5" path="/route5" host="c.example.com">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route6" path="/route6">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route11" path="/route11" host="{var1}.example.com">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route12" path="/route12" host="{var1}.example.com">
    <default key="var1">val</default>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route13" path="/route13/{name}" host="{var1}.example.com">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route14" path="/route14/{name}" host="{var1}.example.com">
    <default key="var1">val</default>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route15" path="/route15/{name}" host="c.example.com">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route16" path="/route16/{name}">
    <default key="var1">val</default>
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
  <route id="route17" path="/route17">
    <option key="compiler_class">Symfony\Component\Routing\RouteCompiler</option>
  </route>
</routes>

=== symfony/symfony/src/Symfony/Component/Routing/Tests/Fixtures/list_in_map_defaults.xml
<?xml version="1.0" encoding="UTF-8" ?>
<routes xmlns="http://symfony.com/schema/routing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/routing
        https://symfony.com/schema/routing/routing-1.0.xsd">

    <route id="blog" path="/blog">
        <default key="_controller">
            <string>AcmeBlogBundle:Blog:index</string>
        </default>
        <default key="values">
            <map>
                <list key="list">
                    <bool>true</bool>
                    <int>1</int>
                    <float>3.5</float>
                    <string>foo</string>
                </list>
            </map>
        </default>
    </route>
</routes>
